<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BooksBeanService" targetNamespace="http://session.ejb.example.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://session.ejb.example.com/" xmlns:ns1="http://remote.session.ejb.example.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://remote.session.ejb.example.com/" location="BooksRemote.wsdl">
    </wsdl:import>
  <wsdl:binding name="BooksBeanServiceSoapBinding" type="ns1:BooksRemote">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="save">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="save">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="saveResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="BusinessException">
        <soap:fault name="BusinessException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="findAll">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="findAll">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="findAllResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getCover">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getCover">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getCoverResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="findById">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="findById">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="findByIdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="saveCover">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="saveCover">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="saveCoverResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BooksBeanService">
    <wsdl:port name="BooksBeanPort" binding="tns:BooksBeanServiceSoapBinding">
      <soap:address location="http://localhost:8080/app-ejb-project-0.0.1-SNAPSHOT/BooksBean?wsdl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
