<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://process.service.ws.web.example.com/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http"
	name="LongProcessService" targetNamespace="http://process.service.ws.web.example.com/">
	<wsdl:types>
		<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:tns="http://process.service.ws.web.example.com/"
			elementFormDefault="unqualified" targetNamespace="http://process.service.ws.web.example.com/"
			version="1.0">
			<xs:element name="run" type="tns:run" />
			<xs:element name="runResponse" type="tns:runResponse" />
			<xs:complexType name="run">
				<xs:sequence>
					<xs:element minOccurs="0" name="arg0" type="xs:string" />
				</xs:sequence>
			</xs:complexType>
			<xs:complexType name="runResponse">
				<xs:sequence>
					<xs:element minOccurs="0" name="return" type="xs:string" />
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="runResponse">
		<wsdl:part element="tns:runResponse" name="parameters"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="run">
		<wsdl:part element="tns:run" name="parameters"></wsdl:part>
	</wsdl:message>
	<wsdl:portType name="LongProcessServicePortType">
		<wsdl:operation name="run">
			<wsdl:input message="tns:run" name="run"></wsdl:input>
			<wsdl:output message="tns:runResponse" name="runResponse"></wsdl:output>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="LongProcessServiceSoapBinding" type="tns:LongProcessServicePortType">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="run">
			<soap:operation soapAction="" style="document" />
			<wsdl:input name="run">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="runResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="LongProcessService">
		<wsdl:port binding="tns:LongProcessServiceSoapBinding" name="LongProcessServicePort">
			<soap:address
				location="http://localhost:8080/app-war-project/LongProcessService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>