
package com.example.ws.topdown.rpc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "productResponseFault", targetNamespace = "http://www.example.org/TopDownRpcService/")
public class RegisterProductFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProductResponseFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RegisterProductFault(String message, ProductResponseFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RegisterProductFault(String message, ProductResponseFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.ws.topdown.rpc.ProductResponseFault
     */
    public ProductResponseFault getFaultInfo() {
        return faultInfo;
    }

}
