
package com.example.ws.topdown.rpc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * RPC/literal service, WS-I BP allows document/literal or rpc/literal only
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TopDownRpcService", targetNamespace = "http://www.example.org/TopDownRpcService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TopDownRpcService {


    /**
     * Notice SOAP Message wraps parts into an element named 'registerProduct', same with output
     * 
     * @param price
     * @param name
     * @param weight
     * @param label
     * @param tag
     * @return
     *     returns com.example.ws.rpc.topdown.ProductResponse
     * @throws RegisterProductFault
     */
    @WebMethod(action = "http://www.example.org/TopDownRpcService/registerProduct")
    @WebResult(name = "registerProductResponse", partName = "registerProductResponse")
    public ProductResponse registerProduct(
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "weight", partName = "weight")
        String weight,
        @WebParam(name = "label", partName = "label")
        String label,
        @WebParam(name = "tag", partName = "tag")
        String tag,
        @WebParam(name = "price", partName = "price")
        double price)
        throws RegisterProductFault
    ;

}
