
package com.example.ws.topdown.rpc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TopDownRpcService", targetNamespace = "http://www.example.org/TopDownRpcService/", wsdlLocation = "file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/TopDownRpcService.wsdl")
public class TopDownRpcService_Service
    extends Service
{

    private final static URL TOPDOWNRPCSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOPDOWNRPCSERVICE_EXCEPTION;
    private final static QName TOPDOWNRPCSERVICE_QNAME = new QName("http://www.example.org/TopDownRpcService/", "TopDownRpcService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/TopDownRpcService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOPDOWNRPCSERVICE_WSDL_LOCATION = url;
        TOPDOWNRPCSERVICE_EXCEPTION = e;
    }

    public TopDownRpcService_Service() {
        super(__getWsdlLocation(), TOPDOWNRPCSERVICE_QNAME);
    }

    public TopDownRpcService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOPDOWNRPCSERVICE_QNAME, features);
    }

    public TopDownRpcService_Service(URL wsdlLocation) {
        super(wsdlLocation, TOPDOWNRPCSERVICE_QNAME);
    }

    public TopDownRpcService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOPDOWNRPCSERVICE_QNAME, features);
    }

    public TopDownRpcService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TopDownRpcService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TopDownRpcService
     */
    @WebEndpoint(name = "TopDownRpcServiceSOAP")
    public TopDownRpcService getTopDownRpcServiceSOAP() {
        return super.getPort(new QName("http://www.example.org/TopDownRpcService/", "TopDownRpcServiceSOAP"), TopDownRpcService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TopDownRpcService
     */
    @WebEndpoint(name = "TopDownRpcServiceSOAP")
    public TopDownRpcService getTopDownRpcServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/TopDownRpcService/", "TopDownRpcServiceSOAP"), TopDownRpcService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOPDOWNRPCSERVICE_EXCEPTION!= null) {
            throw TOPDOWNRPCSERVICE_EXCEPTION;
        }
        return TOPDOWNRPCSERVICE_WSDL_LOCATION;
    }

}
