package com.example.ws.process;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-06-06T15:31:30.100-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "ProcessManagerService", 
                  wsdlLocation = "file:/C:/opt/javaexamples/cxf-project/src/main/resources/ProcessManagerService.wsdl",
                  targetNamespace = "http://www.example.com/ProcessManagerService/") 
public class ProcessManagerService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.com/ProcessManagerService/", "ProcessManagerService");
    public final static QName ProcessManagerServiceSOAP = new QName("http://www.example.com/ProcessManagerService/", "ProcessManagerServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/cxf-project/src/main/resources/ProcessManagerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProcessManagerService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/opt/javaexamples/cxf-project/src/main/resources/ProcessManagerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProcessManagerService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProcessManagerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessManagerService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProcessManagerService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProcessManagerService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProcessManagerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProcessManagerService
     */
    @WebEndpoint(name = "ProcessManagerServiceSOAP")
    public ProcessManagerService getProcessManagerServiceSOAP() {
        return super.getPort(ProcessManagerServiceSOAP, ProcessManagerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessManagerService
     */
    @WebEndpoint(name = "ProcessManagerServiceSOAP")
    public ProcessManagerService getProcessManagerServiceSOAP(WebServiceFeature... features) {
        return super.getPort(ProcessManagerServiceSOAP, ProcessManagerService.class, features);
    }

}
