package com.example.ws.process;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-24T11:30:32.963-05:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.example.com/ProcessManagerService/", name = "ProcessManagerService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProcessManagerService {

    @WebMethod(action = "http://www.example.com/ProcessManagerService/checkProcessStatus")
    @Action(input = "checkProcessRequest", output = "checkProcessResponse")
    @WebResult(name = "checkProcessStatusResponse", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
    public CheckProcessStatusResponse checkProcessStatus(
        @WebParam(partName = "parameters", name = "checkProcessStatusRequest", targetNamespace = "http://www.example.com/ProcessManagerService/")
        CheckProcessStatusRequest parameters
    );

    @WebMethod(action = "http://www.example.com/ProcessManagerService/finishProcess")
    @Action(input = "http://www.example.com/finishProcessRequest", output = "http://www.example.com/finishProcessResponse")
    @WebResult(name = "finishProcessResponse", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
    public FinishProcessResponse finishProcess(
        @WebParam(partName = "parameters", name = "finishProcessRequest", targetNamespace = "http://www.example.com/ProcessManagerService/")
        FinishProcessRequest parameters
    );

    @WebMethod(action = "http://www.example.com/ProcessManagerService/startProcess")
    @Action(input = "http://www.example.com/ProcessManagerService/startProcessRequest", output = "http://www.example.com/ProcessManagerService/startProcessResponse")
    @WebResult(name = "startProcessResponse", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
    public StartProcessResponse startProcess(
        @WebParam(partName = "parameters", name = "startProcessRequest", targetNamespace = "http://www.example.com/ProcessManagerService/")
        StartProcessRequest parameters
    );
}
