package com.example.web.ws.service.longprocessservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2017-04-22T18:09:07.622-05:00
 * Generated source version: 3.1.0
 * 
 */
@WebServiceClient(name = "LongProcessService", 
                  wsdlLocation = "file:/C:/opt/javaexamples/app-java-ee/app-war-project/src/main/resources/wsdl/LongProcessService.wsdl",
                  targetNamespace = "http://service.ws.web.example.com/LongProcessService/") 
public class LongProcessService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.web.example.com/LongProcessService/", "LongProcessService");
    public final static QName LongProcessServiceHTTP = new QName("http://service.ws.web.example.com/LongProcessService/", "LongProcessServiceHTTP");
    public final static QName LongProcessServiceSOAP = new QName("http://service.ws.web.example.com/LongProcessService/", "LongProcessServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/app-java-ee/app-war-project/src/main/resources/wsdl/LongProcessService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LongProcessService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/opt/javaexamples/app-java-ee/app-war-project/src/main/resources/wsdl/LongProcessService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LongProcessService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LongProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LongProcessService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LongProcessService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LongProcessService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LongProcessService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LongProcessServicePort
     */
    @WebEndpoint(name = "LongProcessServiceHTTP")
    public LongProcessServicePort getLongProcessServiceHTTP() {
        return super.getPort(LongProcessServiceHTTP, LongProcessServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LongProcessServicePort
     */
    @WebEndpoint(name = "LongProcessServiceHTTP")
    public LongProcessServicePort getLongProcessServiceHTTP(WebServiceFeature... features) {
        return super.getPort(LongProcessServiceHTTP, LongProcessServicePort.class, features);
    }


    /**
     *
     * @return
     *     returns LongProcessServicePort
     */
    @WebEndpoint(name = "LongProcessServiceSOAP")
    public LongProcessServicePort getLongProcessServiceSOAP() {
        return super.getPort(LongProcessServiceSOAP, LongProcessServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LongProcessServicePort
     */
    @WebEndpoint(name = "LongProcessServiceSOAP")
    public LongProcessServicePort getLongProcessServiceSOAP(WebServiceFeature... features) {
        return super.getPort(LongProcessServiceSOAP, LongProcessServicePort.class, features);
    }

}
