package com.example.web.ws.service.longprocessservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2017-04-22T18:09:07.481-05:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://service.ws.web.example.com/LongProcessService/", name = "LongProcessServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface LongProcessServicePort {

    @WebMethod(action = "http://service.ws.web.example.com/LongProcessService/runProcess")
    @RequestWrapper(localName = "runProcess", targetNamespace = "http://service.ws.web.example.com/LongProcessService/", className = "com.example.web.ws.service.longprocessservice.RunProcess")
    @ResponseWrapper(localName = "runProcessResponse", targetNamespace = "http://service.ws.web.example.com/LongProcessService/", className = "com.example.web.ws.service.longprocessservice.RunProcessResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String runProcess(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    ) throws RunProcessFault_Exception;
}
