
package com.example.web.ws.service.longprocessservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.0
 * 2017-04-22T18:09:07.374-05:00
 * Generated source version: 3.1.0
 */

@WebFault(name = "runProcessFault", targetNamespace = "http://service.ws.web.example.com/LongProcessService/")
public class RunProcessFault_Exception extends Exception {
    
    private com.example.web.ws.service.longprocessservice.RunProcessFault runProcessFault;

    public RunProcessFault_Exception() {
        super();
    }
    
    public RunProcessFault_Exception(String message) {
        super(message);
    }
    
    public RunProcessFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RunProcessFault_Exception(String message, com.example.web.ws.service.longprocessservice.RunProcessFault runProcessFault) {
        super(message);
        this.runProcessFault = runProcessFault;
    }

    public RunProcessFault_Exception(String message, com.example.web.ws.service.longprocessservice.RunProcessFault runProcessFault, Throwable cause) {
        super(message, cause);
        this.runProcessFault = runProcessFault;
    }

    public com.example.web.ws.service.longprocessservice.RunProcessFault getFaultInfo() {
        return this.runProcessFault;
    }
}
