version: "3.1"
services: 
  products-database:
    image: 'mongo'
    container_name:  'products-mongo-database'
    environment: 
      - MONGO_INITDB_DATABASE=productsdb
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017:27017'
  mongo-express:
    depends_on:
      -  products-database
    image: mongo-express
    container_name: 'products-mongo-admin'
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sa
      ME_CONFIG_MONGODB_ADMINPASSWORD: db
      ME_CONFIG_MONGODB_SERVER: products-database
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      
     
      