//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.02 at 03:52:31 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tempuri.org/po.xsd")
package com.example.ws.model.orders;
