
package com.example.ws.process.features;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeaturesRPCPortType", targetNamespace = "http://www.example.org/FeaturesService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FeaturesRPCPortType {


    /**
     * 
     * @param number
     * @param numbers
     * @throws FibNumbersFault
     */
    @WebMethod(action = "fibNumbersSOAPAction")
    public void getFibNumbersRPC(
        @WebParam(name = "number", partName = "number")
        int number,
        @WebParam(name = "numbers", mode = WebParam.Mode.OUT, partName = "numbers")
        Holder<Numbers> numbers)
        throws FibNumbersFault
    ;

}
