
package com.example.ws.process.features;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FeaturesService", targetNamespace = "http://www.example.org/FeaturesService/", wsdlLocation = "file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/FeaturesService.wsdl")
public class FeaturesService
    extends Service
{

    private final static URL FEATURESSERVICE_WSDL_LOCATION;
    private final static WebServiceException FEATURESSERVICE_EXCEPTION;
    private final static QName FEATURESSERVICE_QNAME = new QName("http://www.example.org/FeaturesService/", "FeaturesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/FeaturesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FEATURESSERVICE_WSDL_LOCATION = url;
        FEATURESSERVICE_EXCEPTION = e;
    }

    public FeaturesService() {
        super(__getWsdlLocation(), FEATURESSERVICE_QNAME);
    }

    public FeaturesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FEATURESSERVICE_QNAME, features);
    }

    public FeaturesService(URL wsdlLocation) {
        super(wsdlLocation, FEATURESSERVICE_QNAME);
    }

    public FeaturesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FEATURESSERVICE_QNAME, features);
    }

    public FeaturesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FeaturesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FeaturesRPCPortType
     */
    @WebEndpoint(name = "FeaturesServiceRPCPort")
    public FeaturesRPCPortType getFeaturesServiceRPCPort() {
        return super.getPort(new QName("http://www.example.org/FeaturesService/", "FeaturesServiceRPCPort"), FeaturesRPCPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeaturesRPCPortType
     */
    @WebEndpoint(name = "FeaturesServiceRPCPort")
    public FeaturesRPCPortType getFeaturesServiceRPCPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/FeaturesService/", "FeaturesServiceRPCPort"), FeaturesRPCPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns FeaturesPortType
     */
    @WebEndpoint(name = "FeaturesServiceDocumentPort")
    public FeaturesPortType getFeaturesServiceDocumentPort() {
        return super.getPort(new QName("http://www.example.org/FeaturesService/", "FeaturesServiceDocumentPort"), FeaturesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FeaturesPortType
     */
    @WebEndpoint(name = "FeaturesServiceDocumentPort")
    public FeaturesPortType getFeaturesServiceDocumentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/FeaturesService/", "FeaturesServiceDocumentPort"), FeaturesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FEATURESSERVICE_EXCEPTION!= null) {
            throw FEATURESSERVICE_EXCEPTION;
        }
        return FEATURESSERVICE_WSDL_LOCATION;
    }

}
