
package com.example.ws.process.features;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FeaturesPortType", targetNamespace = "http://www.example.org/FeaturesService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FeaturesPortType {


    /**
     * 
     * @param number
     * @param numbers
     * @throws FibNumbersFault
     */
    @WebMethod(action = "fibNumbersSOAPAction")
    public void getFibNumbers(
        @WebParam(name = "number", targetNamespace = "http://www.example.org/FeaturesTypes", partName = "number")
        int number,
        @WebParam(name = "numbers", targetNamespace = "http://www.example.org/FeaturesTypes", mode = WebParam.Mode.OUT, partName = "numbers")
        Holder<Numbers> numbers)
        throws FibNumbersFault
    ;

}
