
package com.example.ws.topdown;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TopDownService", targetNamespace = "http://topdown.ws.example.com/TopDownService/", wsdlLocation = "file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/TopDownService.wsdl")
public class TopDownService_Service
    extends Service
{

    private final static URL TOPDOWNSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOPDOWNSERVICE_EXCEPTION;
    private final static QName TOPDOWNSERVICE_QNAME = new QName("http://topdown.ws.example.com/TopDownService/", "TopDownService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/TopDownService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOPDOWNSERVICE_WSDL_LOCATION = url;
        TOPDOWNSERVICE_EXCEPTION = e;
    }

    public TopDownService_Service() {
        super(__getWsdlLocation(), TOPDOWNSERVICE_QNAME);
    }

    public TopDownService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOPDOWNSERVICE_QNAME, features);
    }

    public TopDownService_Service(URL wsdlLocation) {
        super(wsdlLocation, TOPDOWNSERVICE_QNAME);
    }

    public TopDownService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOPDOWNSERVICE_QNAME, features);
    }

    public TopDownService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TopDownService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TopDownService
     */
    @WebEndpoint(name = "TopDownServiceSOAP")
    public TopDownService getTopDownServiceSOAP() {
        return super.getPort(new QName("http://topdown.ws.example.com/TopDownService/", "TopDownServiceSOAP"), TopDownService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TopDownService
     */
    @WebEndpoint(name = "TopDownServiceSOAP")
    public TopDownService getTopDownServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://topdown.ws.example.com/TopDownService/", "TopDownServiceSOAP"), TopDownService.class, features);
    }

    /**
     * 
     * @return
     *     returns TopDownService
     */
    @WebEndpoint(name = "TopDownServiceSOAP1")
    public TopDownService getTopDownServiceSOAP1() {
        return super.getPort(new QName("http://topdown.ws.example.com/TopDownService/", "TopDownServiceSOAP1"), TopDownService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TopDownService
     */
    @WebEndpoint(name = "TopDownServiceSOAP1")
    public TopDownService getTopDownServiceSOAP1(WebServiceFeature... features) {
        return super.getPort(new QName("http://topdown.ws.example.com/TopDownService/", "TopDownServiceSOAP1"), TopDownService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOPDOWNSERVICE_EXCEPTION!= null) {
            throw TOPDOWNSERVICE_EXCEPTION;
        }
        return TOPDOWNSERVICE_WSDL_LOCATION;
    }

}
