
package com.example.ws.topdown;

import java.awt.Image;
import javax.activation.DataHandler;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TopDownService", targetNamespace = "http://topdown.ws.example.com/TopDownService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TopDownService {


    /**
     * Example using SOAP With Attachments (SWARef) for response
     * 
     * @param in
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/downloadImage")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://www.example.org/ServiceTypes", className = "com.example.ws.topdown.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://www.example.org/ServiceTypes", className = "com.example.ws.topdown.DownloadImageResponse")
    public DataHandler downloadImage(
        @WebParam(name = "in", targetNamespace = "")
        String in);

    /**
     * Example using MIME Attachments with jaxws:enableMIMEContext:true (allows contentType resolution)
     * 
     * @param file
     * @param parameters
     * @param status
     * @param fileResponse
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/resizeImage")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void resizeImage(
        @WebParam(name = "resizeImageRequest", targetNamespace = "http://www.example.org/ServiceTypes", partName = "parameters")
        ResizeImageRequest parameters,
        @WebParam(name = "file", targetNamespace = "", partName = "file")
        Image file,
        @WebParam(name = "resizeImageResponse", targetNamespace = "http://www.example.org/ServiceTypes", mode = WebParam.Mode.OUT, partName = "status")
        Holder<ResizeImageResponse> status,
        @WebParam(name = "fileResponse", targetNamespace = "", mode = WebParam.Mode.OUT, partName = "fileResponse")
        Holder<Image> fileResponse);

    /**
     * Example using MTOM (XOP:Include in SOAP)
     * 
     * @param registerUser
     * @return
     *     returns com.example.ws.topdown.RegisterUserResponse
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/registerUser")
    @WebResult(name = "registerUserResponse", targetNamespace = "http://www.example.org/ServiceTypes", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RegisterUserResponse registerUser(
        @WebParam(name = "BasicInfo", targetNamespace = "http://www.example.org/ServiceTypes", partName = "registerUser")
        BasicInfo registerUser);

    /**
     * Example of defining SOAP Binding elements (header, fault, headerfault)
     * 
     * @param transactionHeader
     * @param parameters
     * @return
     *     returns com.example.ws.topdown.LookUpUserResponse
     * @throws LookUpUserFault_Exception
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/lookUpUser")
    @WebResult(name = "lookUpUserResponse", targetNamespace = "http://www.example.org/ServiceTypes", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public LookUpUserResponse lookUpUser(
        @WebParam(name = "lookUpUser", targetNamespace = "http://www.example.org/ServiceTypes", partName = "parameters")
        LookUpUser parameters,
        @WebParam(name = "transactionHeader", targetNamespace = "http://www.example.org/ServiceTypes", header = true, partName = "transactionHeader")
        TransactionHeader transactionHeader)
        throws LookUpUserFault_Exception
    ;

    /**
     * One Way Operation Using WS Addressing
     * 
     * @param in
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/evaluateUser")
    @Oneway
    @RequestWrapper(localName = "evaluateUser", targetNamespace = "http://www.example.org/ServiceTypes", className = "com.example.ws.topdown.EvaluateUser")
    @Action(input = "http://topdown.ws.example.com/TopDownService/evaluateUserAction")
    public void evaluateUser(
        @WebParam(name = "in", targetNamespace = "")
        String in);

}
