
package com.example.ws.topdown;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TopDownService", targetNamespace = "http://topdown.ws.example.com/TopDownService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TopDownService {


    /**
     * 
     * @param in
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/downloadImage")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "downloadImage", targetNamespace = "http://www.example.org/ServiceTypes", className = "com.example.ws.topdown.DownloadImage")
    @ResponseWrapper(localName = "downloadImageResponse", targetNamespace = "http://www.example.org/ServiceTypes", className = "com.example.ws.topdown.DownloadImageResponse")
    public String downloadImage(
        @WebParam(name = "in", targetNamespace = "")
        String in);

    /**
     * 
     * @param basicInfo
     * @return
     *     returns com.example.ws.topdown.RegisterUserResponse
     */
    @WebMethod(action = "http://topdown.ws.example.com/TopDownService/registerUser")
    @WebResult(name = "registerUserResponse", targetNamespace = "http://www.example.org/ServiceTypes", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RegisterUserResponse registerUser(
        @WebParam(name = "BasicInfo", targetNamespace = "http://www.example.org/ServiceTypes", partName = "basicInfo")
        BasicInfo basicInfo);

}
