
package com.example.ws.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandomServiceImplService", targetNamespace = "http://service.ws.example.com/", wsdlLocation = "http://localhost:8888/rs?wsdl")
public class RandomServiceImplService
    extends Service
{

    private final static URL RANDOMSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDOMSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RANDOMSERVICEIMPLSERVICE_QNAME = new QName("http://service.ws.example.com/", "RandomServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/rs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDOMSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RANDOMSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RandomServiceImplService() {
        super(__getWsdlLocation(), RANDOMSERVICEIMPLSERVICE_QNAME);
    }

    public RandomServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDOMSERVICEIMPLSERVICE_QNAME, features);
    }

    public RandomServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RANDOMSERVICEIMPLSERVICE_QNAME);
    }

    public RandomServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDOMSERVICEIMPLSERVICE_QNAME, features);
    }

    public RandomServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandomServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RandomService
     */
    @WebEndpoint(name = "RandomServiceImplPort")
    public RandomService getRandomServiceImplPort() {
        return super.getPort(new QName("http://service.ws.example.com/", "RandomServiceImplPort"), RandomService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomService
     */
    @WebEndpoint(name = "RandomServiceImplPort")
    public RandomService getRandomServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.example.com/", "RandomServiceImplPort"), RandomService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDOMSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RANDOMSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RANDOMSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
