
package com.example.ws.service.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomService", targetNamespace = "http://service.ws.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandomService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "next", targetNamespace = "http://service.ws.example.com/", className = "com.example.ws.service.client.Next")
    @ResponseWrapper(localName = "nextResponse", targetNamespace = "http://service.ws.example.com/", className = "com.example.ws.service.client.NextResponse")
    @Action(input = "http://service.ws.example.com/RandomService/nextRequest", output = "http://service.ws.example.com/RandomService/nextResponse")
    public int next();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://service.ws.example.com/", className = "com.example.ws.service.client.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://service.ws.example.com/", className = "com.example.ws.service.client.NextNResponse")
    @Action(input = "http://service.ws.example.com/RandomService/nextNRequest", output = "http://service.ws.example.com/RandomService/nextNResponse")
    public List<Integer> nextN(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
