
package com.example.ws.process.manager.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessClientService", targetNamespace = "http://www.example.com/ProcessClientService/", wsdlLocation = "file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/ProcessClientService.wsdl")
public class ProcessClientService_Service
    extends Service
{

    private final static URL PROCESSCLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSCLIENTSERVICE_EXCEPTION;
    private final static QName PROCESSCLIENTSERVICE_QNAME = new QName("http://www.example.com/ProcessClientService/", "ProcessClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/ProcessClientService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSCLIENTSERVICE_WSDL_LOCATION = url;
        PROCESSCLIENTSERVICE_EXCEPTION = e;
    }

    public ProcessClientService_Service() {
        super(__getWsdlLocation(), PROCESSCLIENTSERVICE_QNAME);
    }

    public ProcessClientService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSCLIENTSERVICE_QNAME, features);
    }

    public ProcessClientService_Service(URL wsdlLocation) {
        super(wsdlLocation, PROCESSCLIENTSERVICE_QNAME);
    }

    public ProcessClientService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSCLIENTSERVICE_QNAME, features);
    }

    public ProcessClientService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessClientService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessClientService
     */
    @WebEndpoint(name = "ProcessClientServiceSOAP")
    public ProcessClientService getProcessClientServiceSOAP() {
        return super.getPort(new QName("http://www.example.com/ProcessClientService/", "ProcessClientServiceSOAP"), ProcessClientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessClientService
     */
    @WebEndpoint(name = "ProcessClientServiceSOAP")
    public ProcessClientService getProcessClientServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/ProcessClientService/", "ProcessClientServiceSOAP"), ProcessClientService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSCLIENTSERVICE_EXCEPTION!= null) {
            throw PROCESSCLIENTSERVICE_EXCEPTION;
        }
        return PROCESSCLIENTSERVICE_WSDL_LOCATION;
    }

}
