
package com.example.app.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BooksBeanService", targetNamespace = "http://session.ejb.example.com/", wsdlLocation = "file:/C:/opt/javaexamples/app-java-ee/app-ejb-project/src/main/resources/wsdl/BookService.wsdl")
public class BooksBeanService
    extends Service
{

    private final static URL BOOKSBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSBEANSERVICE_EXCEPTION;
    private final static QName BOOKSBEANSERVICE_QNAME = new QName("http://session.ejb.example.com/", "BooksBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/app-java-ee/app-ejb-project/src/main/resources/wsdl/BookService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSBEANSERVICE_WSDL_LOCATION = url;
        BOOKSBEANSERVICE_EXCEPTION = e;
    }

    public BooksBeanService() {
        super(__getWsdlLocation(), BOOKSBEANSERVICE_QNAME);
    }

    public BooksBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSBEANSERVICE_QNAME, features);
    }

    public BooksBeanService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSBEANSERVICE_QNAME);
    }

    public BooksBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSBEANSERVICE_QNAME, features);
    }

    public BooksBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BooksBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BooksRemote
     */
    @WebEndpoint(name = "BooksBeanPort")
    public BooksRemote getBooksBeanPort() {
        return super.getPort(new QName("http://session.ejb.example.com/", "BooksBeanPort"), BooksRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BooksRemote
     */
    @WebEndpoint(name = "BooksBeanPort")
    public BooksRemote getBooksBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://session.ejb.example.com/", "BooksBeanPort"), BooksRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSBEANSERVICE_EXCEPTION!= null) {
            throw BOOKSBEANSERVICE_EXCEPTION;
        }
        return BOOKSBEANSERVICE_WSDL_LOCATION;
    }

}
