
package com.example.app.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BooksRemote", targetNamespace = "http://remote.session.ejb.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BooksRemote {


    /**
     * 
     * @return
     *     returns com.example.app.ws.client.BookArray
     */
    @WebMethod
    @WebResult(name = "booksPart", partName = "booksPart")
    public BookArray findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.app.ws.client.Book
     */
    @WebMethod
    @WebResult(name = "bookPart", partName = "bookPart")
    public Book findById(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

}
