
package com.example.ws.process.manager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessManagerService", targetNamespace = "http://www.example.com/ProcessManagerService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessManagerService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.ws.process.manager.StartProcessResponse
     */
    @WebMethod(action = "http://www.example.com/ProcessManagerService/startProcess")
    @WebResult(name = "startProcessResponse", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
    @Action(input = "http://www.example.com/ProcessManagerService/checkProcessRequest", output = "http://www.example.com/ProcessManagerService/checkProcessResponse")
    public StartProcessResponse startProcess(
        @WebParam(name = "startProcessRequest", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
        StartProcessRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.ws.process.manager.CheckProcessStatusResponse
     */
    @WebMethod(action = "http://www.example.com/ProcessManagerService/checkProcessStatus")
    @WebResult(name = "checkProcessStatusResponse", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
    @Action(input = "checkProcessRequest", output = "checkProcessResponse")
    public CheckProcessStatusResponse checkProcessStatus(
        @WebParam(name = "checkProcessStatusRequest", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
        CheckProcessStatusRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.example.ws.process.manager.FinishProcessResponse
     */
    @WebMethod(action = "http://www.example.com/ProcessManagerService/finishProcess")
    @WebResult(name = "finishProcessResponse", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
    @Action(input = "http://www.example.com/finishProcessRequest", output = "http://www.example.com/finishProcessResponse")
    public FinishProcessResponse finishProcess(
        @WebParam(name = "finishProcessRequest", targetNamespace = "http://www.example.com/ProcessManagerService/", partName = "parameters")
        FinishProcessRequest parameters);

}
