
package com.example.ws.process.manager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessClientService", targetNamespace = "http://www.example.com/ProcessClientService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessClientService {


    /**
     * 
     * @param processResumedRequest
     * @return
     *     returns com.example.ws.process.manager.ProcessResumedResponse
     */
    @WebMethod(action = "http://www.example.com/ProcessClientService/processResumed")
    @WebResult(name = "processResumedResponse", targetNamespace = "http://www.example.com/ProcessClientService/", partName = "processResumedResponse")
    public ProcessResumedResponse processResumed(
        @WebParam(name = "processResumedRequest", targetNamespace = "http://www.example.com/ProcessClientService/", partName = "processResumedRequest")
        ProcessResumedRequest processResumedRequest);

}
