
package com.example.ws.process.manager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessManagerService", targetNamespace = "http://www.example.com/ProcessManagerService/", wsdlLocation = "file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/ProcessManagerService.wsdl")
public class ProcessManagerService_Service
    extends Service
{

    private final static URL PROCESSMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSMANAGERSERVICE_EXCEPTION;
    private final static QName PROCESSMANAGERSERVICE_QNAME = new QName("http://www.example.com/ProcessManagerService/", "ProcessManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/opt/javaexamples/jaxws-local/src/main/webapp/WEB-INF/wsdl/ProcessManagerService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSMANAGERSERVICE_WSDL_LOCATION = url;
        PROCESSMANAGERSERVICE_EXCEPTION = e;
    }

    public ProcessManagerService_Service() {
        super(__getWsdlLocation(), PROCESSMANAGERSERVICE_QNAME);
    }

    public ProcessManagerService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSMANAGERSERVICE_QNAME, features);
    }

    public ProcessManagerService_Service(URL wsdlLocation) {
        super(wsdlLocation, PROCESSMANAGERSERVICE_QNAME);
    }

    public ProcessManagerService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSMANAGERSERVICE_QNAME, features);
    }

    public ProcessManagerService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessManagerService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessManagerService
     */
    @WebEndpoint(name = "ProcessManagerServiceSOAP")
    public ProcessManagerService getProcessManagerServiceSOAP() {
        return super.getPort(new QName("http://www.example.com/ProcessManagerService/", "ProcessManagerServiceSOAP"), ProcessManagerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessManagerService
     */
    @WebEndpoint(name = "ProcessManagerServiceSOAP")
    public ProcessManagerService getProcessManagerServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/ProcessManagerService/", "ProcessManagerServiceSOAP"), ProcessManagerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSMANAGERSERVICE_EXCEPTION!= null) {
            throw PROCESSMANAGERSERVICE_EXCEPTION;
        }
        return PROCESSMANAGERSERVICE_WSDL_LOCATION;
    }

}
