
package com.example.ws.process.dependency;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DependencyProcessServiceService", targetNamespace = "http://process.ws.example.com", wsdlLocation = "http://localhost:8180/jaxws-local/DependencyProcessService?wsdl")
public class DependencyProcessServiceService
    extends Service
{

    private final static URL DEPENDENCYPROCESSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEPENDENCYPROCESSSERVICESERVICE_EXCEPTION;
    private final static QName DEPENDENCYPROCESSSERVICESERVICE_QNAME = new QName("http://process.ws.example.com", "DependencyProcessServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8180/jaxws-local/DependencyProcessService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPENDENCYPROCESSSERVICESERVICE_WSDL_LOCATION = url;
        DEPENDENCYPROCESSSERVICESERVICE_EXCEPTION = e;
    }

    public DependencyProcessServiceService() {
        super(__getWsdlLocation(), DEPENDENCYPROCESSSERVICESERVICE_QNAME);
    }

    public DependencyProcessServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPENDENCYPROCESSSERVICESERVICE_QNAME, features);
    }

    public DependencyProcessServiceService(URL wsdlLocation) {
        super(wsdlLocation, DEPENDENCYPROCESSSERVICESERVICE_QNAME);
    }

    public DependencyProcessServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPENDENCYPROCESSSERVICESERVICE_QNAME, features);
    }

    public DependencyProcessServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DependencyProcessServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DependencyProcessService
     */
    @WebEndpoint(name = "DependencyProcessServicePort")
    public DependencyProcessService getDependencyProcessServicePort() {
        return super.getPort(new QName("http://process.ws.example.com", "DependencyProcessServicePort"), DependencyProcessService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DependencyProcessService
     */
    @WebEndpoint(name = "DependencyProcessServicePort")
    public DependencyProcessService getDependencyProcessServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://process.ws.example.com", "DependencyProcessServicePort"), DependencyProcessService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPENDENCYPROCESSSERVICESERVICE_EXCEPTION!= null) {
            throw DEPENDENCYPROCESSSERVICESERVICE_EXCEPTION;
        }
        return DEPENDENCYPROCESSSERVICESERVICE_WSDL_LOCATION;
    }

}
