
package com.example.ws.process.dependency;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ProcessException", targetNamespace = "http://process.ws.example.com")
public class ProcessException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProcessException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ProcessException_Exception(String message, ProcessException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ProcessException_Exception(String message, ProcessException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.ws.process.dependency.ProcessException
     */
    public ProcessException getFaultInfo() {
        return faultInfo;
    }

}
